/**
 * AUTO-GENERATED TypeScript definitions from backend Pydantic schemas
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated by: scripts/generate_frontend_types.py
 *
 * These types match the JSON structure returned by backend APIs.
 * They are derived from Pydantic models which extend the adcp library schemas.
 *
 * To regenerate: uv run python scripts/generate_frontend_types.py
 */

export interface Asset {
  /** Identifier for this asset within the group */
  asset_id: string;
  /** Optional descriptive label for this asset's purpose (e.g., 'hero_image', 'logo'). Not used for referencing assets in manifests—use asset_id instead. This field is for human-readable documentation and UI display only. */
  asset_role?: string | null;
  /** Type of asset */
  asset_type: AssetType;
  /** Whether this asset is required in each repetition */
  required?: boolean | null;
  /** Technical requirements for this asset */
  requirements?: Record<string, any> | null;
}

export interface AssetType {
}

export interface AssetsRequired {
  /** Unique identifier for this asset. Creative manifests MUST use this exact value as the key in the assets object. */
  asset_id: string;
  /** Optional descriptive label for this asset's purpose (e.g., 'hero_image', 'logo'). Not used for referencing assets in manifests—use asset_id instead. This field is for human-readable documentation and UI display only. */
  asset_role?: string | null;
  /** Type of asset */
  asset_type: AssetType;
  /** Discriminator indicating this is an individual asset requirement */
  item_type: string;
  /** Whether this asset is required */
  required?: boolean | null;
  /** Technical requirements for this asset (dimensions, file size, duration, etc.) */
  requirements?: Record<string, any> | null;
}

export interface AssetsRequired1 {
  /** Identifier for this asset group (e.g., 'product', 'slide', 'card') */
  asset_group_id: string;
  /** Assets within each repetition of this group */
  assets: Asset[];
  /** Discriminator indicating this is a repeatable asset group */
  item_type: string;
  /** Maximum number of repetitions allowed */
  max_count: number;
  /** Minimum number of repetitions required */
  min_count: number;
}

export interface Dimensions {
  /** Fixed aspect ratio constraint (e.g., '16:9', '4:3', '1:1') */
  aspect_ratio?: string | null;
  /** Fixed height in specified units */
  height?: number | null;
  /** Maximum height for responsive renders */
  max_height?: number | null;
  /** Maximum width for responsive renders */
  max_width?: number | null;
  /** Minimum height for responsive renders */
  min_height?: number | null;
  /** Minimum width for responsive renders */
  min_width?: number | null;
  /** Indicates which dimensions are responsive/fluid */
  responsive?: Responsive | null;
  /** Unit of measurement for dimensions */
  unit: Unit;
  /** Fixed width in specified units */
  width?: number | null;
}

export interface FormatCard {
  /** Creative format defining the card layout (typically format_card_standard) */
  format_id: FormatId;
  /** Asset manifest for rendering the card, structure defined by the format */
  manifest: Record<string, any>;
}

export interface FormatCardDetailed {
  /** Creative format defining the detailed card layout (typically format_card_detailed) */
  format_id: FormatId;
  /** Asset manifest for rendering the detailed card, structure defined by the format */
  manifest: Record<string, any>;
}

export interface FormatId {
  /** URL of the agent that defines this format (e.g., 'https://creative.adcontextprotocol.org' for standard formats, or 'https://publisher.com/.well-known/adcp/sales' for custom formats) */
  agent_url: string;
  /** Format identifier within the agent's namespace (e.g., 'display_300x250', 'video_standard_30s') */
  id: string;
}

export interface Render {
  /** Dimensions for this rendered piece */
  dimensions: Dimensions;
  /** Semantic role of this rendered piece (e.g., 'primary', 'companion', 'mobile_variant') */
  role: string;
}

export interface Responsive {
  height: boolean;
  width: boolean;
}

export interface Type {
}

export interface Unit {
}

export interface Format {
  /** Array of required assets or asset groups for this format. Each asset is identified by its asset_id, which must be used as the key in creative manifests. Can contain individual assets or repeatable asset sequences (e.g., carousel products, slideshow frames). */
  assets_required?: AssetsRequired | AssetsRequired1[] | null;
  /** Delivery method specifications (e.g., hosted, VAST, third-party tags) */
  delivery?: Record<string, any> | null;
  /** Plain text explanation of what this format does and what assets it requires */
  description?: string | null;
  /** Optional URL to showcase page with examples and interactive demos of this format */
  example_url?: string | null;
  /** Optional standard visual card (300x400px) for displaying this format in user interfaces. Can be rendered via preview_creative or pre-generated. */
  format_card?: FormatCard | null;
  /** Optional detailed card with carousel and full specifications. Provides rich format documentation similar to ad spec pages. */
  format_card_detailed?: FormatCardDetailed | null;
  /** Structured format identifier with agent URL and format name */
  format_id: FormatId;
  /** Human-readable format name */
  name: string;
  /** For generative formats: array of format IDs that this format can generate. When a format accepts inputs like brand_manifest and message, this specifies what concrete output formats can be produced (e.g., a generative banner format might output standard image banner formats). */
  output_format_ids?: FormatId[] | null;
  /** DEPRECATED: Use format_card instead. Optional preview image URL for format browsing/discovery UI. Should be 400x300px (4:3 aspect ratio) PNG or JPG. Used as thumbnail/card image in format browsers. This field is maintained for backward compatibility but format_card provides a more flexible, structured approach. */
  preview_image?: string | null;
  /** Specification of rendered pieces for this format. Most formats produce a single render. Companion ad formats (video + banner), adaptive formats, and multi-placement formats produce multiple renders. Each render specifies its role and dimensions. */
  renders?: Render[] | null;
  /** List of universal macros supported by this format (e.g., MEDIA_BUY_ID, CACHEBUSTER, DEVICE_ID). Used for validation and developer tooling. */
  supported_macros?: string[] | null;
  /** Media type of this format - determines rendering method and asset requirements */
  type: Type;
  /** Internal: Platform-specific configuration (e.g., gam, kevel) for creative mapping */
  platform_config?: Record<string, any> | null;
  /** Internal: Format category (not in AdCP spec) */
  category?: string | null;
  /** Internal: Whether this follows IAB specifications (not in AdCP spec) */
  is_standard?: boolean | null;
  /** Internal: Legacy technical specifications (not in AdCP spec, use renders instead) */
  requirements?: Record<string, any> | null;
  /** Internal: Name of IAB specification (not in AdCP spec) */
  iab_specification?: string | null;
  /** Internal: Whether format accepts third-party tags (not in AdCP spec) */
  accepts_3p_tags?: boolean | null;
}

export interface FormatId {
  /** URL of the agent that defines this format (e.g., 'https://creative.adcontextprotocol.org' for standard formats, or 'https://publisher.com/.well-known/adcp/sales' for custom formats) */
  agent_url: string;
  /** Format identifier within the agent's namespace (e.g., 'display_300x250', 'video_standard_30s') */
  id: string;
}

export interface AvailableMetric {
}

export interface AvailableReportingFrequency {
}

export interface CoBranding {
}

export interface CpcPricingOption {
  /** ISO 4217 currency code */
  currency: string;
  /** Minimum spend requirement per package using this pricing option, in the specified currency */
  min_spend_per_package?: number | null;
  /** Cost per click */
  pricing_model: string;
  /** Unique identifier for this pricing option within the product (e.g., 'cpc_usd_fixed') */
  pricing_option_id: string;
  /** Fixed CPC rate (cost per click) */
  rate: number;
}

export interface CpcvPricingOption {
  /** ISO 4217 currency code */
  currency: string;
  /** Minimum spend requirement per package using this pricing option, in the specified currency */
  min_spend_per_package?: number | null;
  /** Cost per completed view (100% completion) */
  pricing_model: string;
  /** Unique identifier for this pricing option within the product (e.g., 'cpcv_usd_guaranteed') */
  pricing_option_id: string;
  /** Fixed CPCV rate (cost per 100% completion) */
  rate: number;
}

export interface CpmAuctionPricingOption {
  /** ISO 4217 currency code */
  currency: string;
  /** Minimum spend requirement per package using this pricing option, in the specified currency */
  min_spend_per_package?: number | null;
  /** Pricing guidance for auction-based CPM bidding */
  price_guidance: adcp__types__generated_poc__cpm_auction_option__PriceGuidance;
  /** Cost per 1,000 impressions */
  pricing_model: string;
  /** Unique identifier for this pricing option within the product (e.g., 'cpm_usd_auction') */
  pricing_option_id: string;
}

export interface CpmFixedRatePricingOption {
  /** ISO 4217 currency code */
  currency: string;
  /** Minimum spend requirement per package using this pricing option, in the specified currency */
  min_spend_per_package?: number | null;
  /** Cost per 1,000 impressions */
  pricing_model: string;
  /** Unique identifier for this pricing option within the product (e.g., 'cpm_usd_guaranteed') */
  pricing_option_id: string;
  /** Fixed CPM rate (cost per 1,000 impressions) */
  rate: number;
}

export interface CppPricingOption {
  /** ISO 4217 currency code */
  currency: string;
  /** Minimum spend requirement per package using this pricing option, in the specified currency */
  min_spend_per_package?: number | null;
  /** CPP-specific parameters for demographic targeting and GRP requirements */
  parameters: adcp__types__generated_poc__cpp_option__Parameters;
  /** Cost per Gross Rating Point */
  pricing_model: string;
  /** Unique identifier for this pricing option within the product (e.g., 'cpp_usd_p18-49') */
  pricing_option_id: string;
  /** Fixed CPP rate (cost per rating point) */
  rate: number;
}

export interface CpvPricingOption {
  /** ISO 4217 currency code */
  currency: string;
  /** Minimum spend requirement per package using this pricing option, in the specified currency */
  min_spend_per_package?: number | null;
  /** CPV-specific parameters defining the view threshold */
  parameters: adcp__types__generated_poc__cpv_option__Parameters;
  /** Cost per view at threshold */
  pricing_model: string;
  /** Unique identifier for this pricing option within the product (e.g., 'cpv_usd_50pct') */
  pricing_option_id: string;
  /** Fixed CPV rate (cost per view) */
  rate: number;
}

export interface CreativePolicy {
  /** Co-branding requirement */
  co_branding: CoBranding;
  /** Landing page requirements */
  landing_page: LandingPage;
  /** Whether creative templates are provided */
  templates_available: boolean;
}

export interface DeliveryMeasurement {
  /** Additional details about measurement methodology in plain language (e.g., 'MRC-accredited viewability. 50% in-view for 1s display / 2s video', 'Panel-based demographic measurement updated monthly') */
  notes?: string | null;
  /** Measurement provider(s) used for this product (e.g., 'Google Ad Manager with IAS viewability', 'Nielsen DAR', 'Geopath for DOOH impressions') */
  provider: string;
}

export interface DeliveryType {
}

export interface FlatRatePricingOption {
  /** ISO 4217 currency code */
  currency: string;
  /** Whether this is a fixed rate (true) or auction-based (false) */
  is_fixed: boolean;
  /** Minimum spend requirement per package using this pricing option, in the specified currency */
  min_spend_per_package?: number | null;
  /** Flat rate parameters for DOOH and time-based campaigns */
  parameters?: adcp__types__generated_poc__flat_rate_option__Parameters | null;
  /** Fixed cost regardless of delivery volume */
  pricing_model: string;
  /** Unique identifier for this pricing option within the product (e.g., 'flat_rate_usd_24h_takeover') */
  pricing_option_id: string;
  /** Flat rate cost */
  rate: number;
}

export interface FormatId {
  /** URL of the agent that defines this format (e.g., 'https://creative.adcontextprotocol.org' for standard formats, or 'https://publisher.com/.well-known/adcp/sales' for custom formats) */
  agent_url: string;
  /** Format identifier within the agent's namespace (e.g., 'display_300x250', 'video_standard_30s') */
  id: string;
}

export interface LandingPage {
}

export interface Measurement {
  /** Attribution methodology */
  attribution: string;
  /** Reporting frequency and format */
  reporting: string;
  /** Type of measurement */
  type: string;
  /** Attribution window */
  window?: string | null;
}

export interface Placement {
  /** Detailed description of where and how the placement appears */
  description?: string | null;
  /** Format IDs supported by this specific placement (subset of product's formats) */
  format_ids?: FormatId[] | null;
  /** Human-readable name for the placement (e.g., 'Homepage Banner', 'Article Sidebar') */
  name: string;
  /** Unique identifier for the placement within the product */
  placement_id: string;
}

export interface ProductCard {
  /** Creative format defining the card layout (typically product_card_standard) */
  format_id: FormatId;
  /** Asset manifest for rendering the card, structure defined by the format */
  manifest: Record<string, any>;
}

export interface ProductCardDetailed {
  /** Creative format defining the detailed card layout (typically product_card_detailed) */
  format_id: FormatId;
  /** Asset manifest for rendering the detailed card, structure defined by the format */
  manifest: Record<string, any>;
}

export interface PropertyId {
}

export interface PropertyTag {
}

export interface PublisherProperties {
  /** Specific property IDs from the publisher's adagents.json */
  property_ids: PropertyId[];
  /** Domain where publisher's adagents.json is hosted (e.g., 'cnn.com') */
  publisher_domain: string;
  /** Discriminator indicating selection by specific property IDs */
  selection_type: string;
}

export interface PublisherProperties3 {
  /** Property tags from the publisher's adagents.json. Product covers all properties with these tags */
  property_tags: PropertyTag[];
  /** Domain where publisher's adagents.json is hosted (e.g., 'cnn.com') */
  publisher_domain: string;
  /** Discriminator indicating selection by property tags */
  selection_type: string;
}

export interface ReportingCapabilities {
  /** Metrics available in reporting. Impressions and spend are always implicitly included. */
  available_metrics: AvailableMetric[];
  /** Supported reporting frequency options */
  available_reporting_frequencies: AvailableReportingFrequency[];
  /** Expected delay in minutes before reporting data becomes available (e.g., 240 for 4-hour delay) */
  expected_delay_minutes: number;
  /** Whether this product supports webhook-based reporting notifications */
  supports_webhooks: boolean;
  /** Timezone for reporting periods. Use 'UTC' or IANA timezone (e.g., 'America/New_York'). Critical for daily/monthly frequency alignment. */
  timezone: string;
}

export interface VcpmAuctionPricingOption {
  /** ISO 4217 currency code */
  currency: string;
  /** Minimum spend requirement per package using this pricing option, in the specified currency */
  min_spend_per_package?: number | null;
  /** Statistical guidance for auction pricing */
  price_guidance: adcp__types__generated_poc__vcpm_auction_option__PriceGuidance;
  /** Cost per 1,000 viewable impressions (MRC standard) */
  pricing_model: string;
  /** Unique identifier for this pricing option within the product (e.g., 'vcpm_usd_auction') */
  pricing_option_id: string;
}

export interface VcpmFixedRatePricingOption {
  /** ISO 4217 currency code */
  currency: string;
  /** Minimum spend requirement per package using this pricing option, in the specified currency */
  min_spend_per_package?: number | null;
  /** Cost per 1,000 viewable impressions (MRC standard) */
  pricing_model: string;
  /** Unique identifier for this pricing option within the product (e.g., 'vcpm_usd_guaranteed') */
  pricing_option_id: string;
  /** Fixed vCPM rate (cost per 1,000 viewable impressions) */
  rate: number;
}

export interface ViewThreshold {
}

export interface ViewThreshold1 {
  /** Seconds of viewing required (e.g., 30 for YouTube-style '30 seconds = view') */
  duration_seconds: number;
}

export interface adcp__types__generated_poc__cpm_auction_option__PriceGuidance {
  /** Minimum bid price - publisher will reject bids under this value */
  floor: number;
  /** 25th percentile winning price */
  p25?: number | null;
  /** Median winning price */
  p50?: number | null;
  /** 75th percentile winning price */
  p75?: number | null;
  /** 90th percentile winning price */
  p90?: number | null;
}

export interface adcp__types__generated_poc__cpp_option__Parameters {
  /** Target demographic in Nielsen format: P/M/W/A/C + age range. Examples: P18-49 (Persons 18-49), M25-54 (Men 25-54), W35+ (Women 35+), A18-34 (Adults 18-34), C2-11 (Children 2-11) */
  demographic: string;
  /** Minimum GRPs/TRPs required for this pricing option */
  min_points?: number | null;
}

export interface adcp__types__generated_poc__cpv_option__Parameters {
  view_threshold: ViewThreshold | ViewThreshold1;
}

export interface adcp__types__generated_poc__flat_rate_option__Parameters {
  /** Specific daypart for time-based pricing (e.g., 'morning_commute', 'evening_prime', 'overnight') */
  daypart?: string | null;
  /** Duration in hours for time-based flat rate pricing (DOOH) */
  duration_hours?: number | null;
  /** Estimated impressions for this flat rate option (informational, commonly used with SOV or time-based DOOH) */
  estimated_impressions?: number | null;
  /** Duration of ad loop rotation in seconds (DOOH) */
  loop_duration_seconds?: number | null;
  /** Minimum number of times ad plays per hour (DOOH frequency guarantee) */
  min_plays_per_hour?: number | null;
  /** Guaranteed share of voice as percentage (DOOH, 0-100) */
  sov_percentage?: number | null;
  /** Named venue package identifier for DOOH (e.g., 'times_square_network', 'airport_terminals') */
  venue_package?: string | null;
}

export interface adcp__types__generated_poc__vcpm_auction_option__PriceGuidance {
  /** Minimum acceptable bid price */
  floor: number;
  /** 25th percentile of recent winning bids */
  p25?: number | null;
  /** Median of recent winning bids */
  p50?: number | null;
  /** 75th percentile of recent winning bids */
  p75?: number | null;
  /** 90th percentile of recent winning bids */
  p90?: number | null;
}

export interface Product {
  /** Explanation of why this product matches the brief (only included when brief is provided) */
  brief_relevance?: string | null;
  creative_policy?: CreativePolicy | null;
  /** Measurement provider and methodology for delivery metrics. The buyer accepts the declared provider as the source of truth for the buy. REQUIRED for all products. */
  delivery_measurement: DeliveryMeasurement;
  delivery_type: DeliveryType;
  /** Detailed description of the product and its inventory */
  description: string;
  /** Estimated exposures/impressions for guaranteed products */
  estimated_exposures?: number | null;
  /** Expiration timestamp for custom products */
  expires_at?: string | null;
  /** Array of supported creative format IDs - structured format_id objects with agent_url and id */
  format_ids: FormatId[];
  /** Whether this is a custom product */
  is_custom?: boolean | null;
  measurement?: Measurement | null;
  /** Human-readable product name */
  name: string;
  /** Optional array of specific placements within this product. When provided, buyers can target specific placements when assigning creatives. */
  placements?: Placement[] | null;
  /** Available pricing models for this product */
  pricing_options: CpmFixedRatePricingOption | CpmAuctionPricingOption | VcpmFixedRatePricingOption | VcpmAuctionPricingOption | CpcPricingOption | CpcvPricingOption | CpvPricingOption | CppPricingOption | FlatRatePricingOption[];
  /** Optional standard visual card (300x400px) for displaying this product in user interfaces. Can be rendered via preview_creative or pre-generated. */
  product_card?: ProductCard | null;
  /** Optional detailed card with carousel and full specifications. Provides rich product presentation similar to media kit pages. */
  product_card_detailed?: ProductCardDetailed | null;
  /** Unique identifier for the product */
  product_id: string;
  /** Publisher properties covered by this product. Buyers fetch actual property definitions from each publisher's adagents.json and validate agent authorization. */
  publisher_properties: PublisherProperties | PublisherProperties3[];
  reporting_capabilities?: ReportingCapabilities | null;
  /** Internal: Ad server-specific configuration for implementing this product */
  implementation_config?: Record<string, any> | null;
}

export interface Creative {
  /** Unique identifier for the creative */
  creative_id: string;
  /** Human-readable creative name */
  name: string;
  /** Creative format identifier with agent_url namespace */
  format_id: FormatId;
  /** Assets required by the format, keyed by asset_role. Values can be image, video, audio, text, html, css, javascript, vast, daast, url, or promoted-offerings assets. */
  assets: Record<string, any>;
  /** Preview contexts for generative formats - defines what scenarios to generate previews for */
  inputs?: Record<string, any>[] | null;
  /** User-defined tags for organization and searchability */
  tags?: string[] | null;
  /** For generative creatives: set to true to approve and finalize, false to request regeneration. Omit for non-generative creatives. */
  approved?: boolean | null;
  principal_id?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  /** Workflow status: pending, approved, rejected */
  status?: string;
}

export interface FormatId {
  /** URL of the agent that defines this format (e.g., 'https://creative.adcontextprotocol.org' for standard formats, or 'https://publisher.com/.well-known/adcp/sales' for custom formats) */
  agent_url: string;
  /** Format identifier within the agent's namespace (e.g., 'display_300x250', 'video_standard_30s') */
  id: string;
}

export interface FrequencyCap {
  /** Suppress impressions for this many minutes after serving */
  suppress_minutes: number;
  /** Apply at media buy or package level */
  scope?: string;
}

export interface PricingModel {
}

export interface Targeting {
  geo_country_any_of?: string[] | null;
  geo_country_none_of?: string[] | null;
  geo_region_any_of?: string[] | null;
  geo_region_none_of?: string[] | null;
  geo_metro_any_of?: string[] | null;
  geo_metro_none_of?: string[] | null;
  geo_city_any_of?: string[] | null;
  geo_city_none_of?: string[] | null;
  geo_zip_any_of?: string[] | null;
  geo_zip_none_of?: string[] | null;
  device_type_any_of?: string[] | null;
  device_type_none_of?: string[] | null;
  os_any_of?: string[] | null;
  os_none_of?: string[] | null;
  browser_any_of?: string[] | null;
  browser_none_of?: string[] | null;
  content_cat_any_of?: string[] | null;
  content_cat_none_of?: string[] | null;
  keywords_any_of?: string[] | null;
  keywords_none_of?: string[] | null;
  audiences_any_of?: string[] | null;
  audiences_none_of?: string[] | null;
  signals?: string[] | null;
  media_type_any_of?: string[] | null;
  media_type_none_of?: string[] | null;
  frequency_cap?: FrequencyCap | null;
  connection_type_any_of?: number[] | null;
  connection_type_none_of?: number[] | null;
  custom?: Record<string, any> | null;
  key_value_pairs?: Record<string, any> | null;
  /** Internal: Tenant ID for multi-tenancy */
  tenant_id?: string | null;
  /** Internal: Creation timestamp */
  created_at?: string | null;
  /** Internal: Last update timestamp */
  updated_at?: string | null;
  /** Internal: Additional metadata */
  metadata?: Record<string, any> | null;
}

export interface Package {
  /** Publisher's unique identifier for the package */
  package_id?: string | null;
  /** Status of the package */
  status?: string | null;
  /** Buyer's reference identifier for this package */
  buyer_ref?: string | null;
  /** ID of the product this package is based on (single product) */
  product_id?: string | null;
  /** Array of product IDs to include in this package */
  products?: string[] | null;
  /** Budget allocation for this package in the currency specified by the pricing option */
  budget?: number | null;
  /** Impression goal for this package */
  impressions?: number | null;
  /** Package-specific targeting */
  targeting_overlay?: Targeting | null;
  /** Creative IDs to assign to this package */
  creative_ids?: string[] | null;
  /** Full creative objects to upload and assign to this package at creation time (alternative to creative_ids) */
  creatives?: Creative[] | null;
  /** Creative assets assigned to this package */
  creative_assignments?: Record<string, any>[] | null;
  /** Format IDs for this package (array of FormatId objects with agent_url and id per AdCP v2.4) */
  format_ids?: FormatId[] | null;
  /** Format IDs that creative assets will be provided for this package (array of FormatId objects per AdCP v2.4) */
  format_ids_to_provide?: FormatId[] | null;
  /** ID of the selected pricing option from the product's pricing_options array (REQUIRED in requests) */
  pricing_option_id?: string | null;
  /** Bid price for auction-based pricing (required if pricing option is auction-based) */
  bid_price?: number | null;
  /** Pacing strategy for this package */
  pacing?: string | null;
  /** DEPRECATED: Use pricing_option_id instead. Selected pricing model for backward compatibility. */
  pricing_model?: PricingModel | null;
  /** Internal: Tenant ID for multi-tenancy */
  tenant_id?: string | null;
  /** Internal: Associated media buy ID */
  media_buy_id?: string | null;
  /** Internal: Platform-specific line item ID for creative association */
  platform_line_item_id?: string | null;
  /** Internal: Creation timestamp */
  created_at?: string | null;
  /** Internal: Last update timestamp */
  updated_at?: string | null;
  /** Internal: Additional metadata */
  metadata?: Record<string, any> | null;
}

export interface PropertyIdentifier {
  /** Type of identifier (e.g., 'domain', 'bundle_id', 'roku_store_id', 'podcast_guid') */
  type: string;
  /** The identifier value. For domain type: 'example.com' matches www.example.com and m.example.com only; 'subdomain.example.com' matches that specific subdomain; '*.example.com' matches all subdomains */
  value: string;
}

export interface Property {
  /** Type of advertising property */
  property_type: string;
  /** Human-readable property name */
  name: string;
  /** Array of identifiers for this property */
  identifiers: PropertyIdentifier[];
  /** Tags for categorization and grouping (e.g., network membership, content categories) */
  tags?: string[] | null;
  /** Domain where adagents.json should be checked for authorization validation */
  publisher_domain: string;
}

export interface FormatId {
  /** URL of the agent that defines this format (e.g., 'https://creative.adcontextprotocol.org' for standard formats, or 'https://publisher.com/.well-known/adcp/sales' for custom formats) */
  agent_url: string;
  /** Format identifier within the agent's namespace (e.g., 'display_300x250', 'video_standard_30s') */
  id: string;
}

export interface Creative {
  /** Unique identifier for the creative */
  creative_id: string;
  /** Human-readable creative name */
  name: string;
  /** Creative format identifier with agent_url namespace */
  format_id: FormatId;
  /** Assets required by the format, keyed by asset_role. Values can be image, video, audio, text, html, css, javascript, vast, daast, url, or promoted-offerings assets. */
  assets: Record<string, any>;
  /** Preview contexts for generative formats - defines what scenarios to generate previews for */
  inputs?: Record<string, any>[] | null;
  /** User-defined tags for organization and searchability */
  tags?: string[] | null;
  /** For generative creatives: set to true to approve and finalize, false to request regeneration. Omit for non-generative creatives. */
  approved?: boolean | null;
  principal_id?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  /** Workflow status: pending, approved, rejected */
  status?: string;
}
